INSERT INTO books (author, name, customer_id)
VALUES
('William Bradford', '1492', '77'),
('Anne Bradstreet', '48 Small Poems', '302'),
('Thomas Harriot', 'XXXVI Lyrics and XII Sonnets', null),
('Increase Mather', 'A Book of Music', '343'),
('Cotton Mather', 'A Book of Romances, Lyrics, and Songs', '449'),
('Thomas Morton', 'A Book of Verses (1898)', '450'),
('Álvar Núñez Cabeza de Vaca', 'A Book-Lover’s Holidays in the Open', null),
('William Penn', 'A Boy’s Will', null),
('Samuel Sewall', 'A Calendar of Sonnets', null),
('John Smith', 'A Cathedral Courtship', null),
('Edward Taylor', 'Accidental Center', null),
('Nathaniel Ward', 'Accolon of Gaul', null),
('Michael Wigglesworth', 'A Connecticut Yankee in King Arthur’s Court', '342'),
('Roger Williams', 'Active Service', '490'),
('John Winthrop', 'A Dog’s Tale', '318'),
('Abigail Adams', 'A Dome of Many-Coloured Glass', '28'),
('Hannah Adams', 'Adventures and Letters of Richard Harding Davis', null),
('John Adams', 'Aesthetics', null),
('Conrad Beissel', 'A Few Figs from Thistles', null),
('Charles Brockden Brown', 'Aftermath', null),
('William Hill Brown', 'After the Armies Have Passed', null),
('William Byrd', 'Afterwhiles', null),
('Jonathan Carver', 'A Heap O’ Livin', '323'),
('Joseph Dennie', 'A Home Idyl, and Other Poems', '487'),
('John Dickinson', 'A Horse’s Tale', '142'),
('Joseph Rodman Drake', 'Airs of Palestine: A Poem', '245'),
('Timothy Dwight', 'Air the Trees', null),
('Jonathan Edwards', 'A Knight of the Nets', null),
('Olaudah Equiano', 'A Lady of Quality', null),
('Elizabeth Graeme Fergusson', 'Alashka', '409'),
('Hannah Webster Foster', 'Alexander’s Bridge', '1'),
('Benjamin Franklin', 'A Little Dreaming', '341'),
('Philip Freneau', 'A Little Princess', null),
('Samuel Griswold Goodrich', 'Alnwick Castle, With Other Poems', null),
('Alexander Hamilton', 'Along the Way', null),
('Samuel Hopkins', 'A Masque and Other Poems', null),
('Thomas Jefferson', 'A Masque of Poets: Including Guy Vernon, a Novelette in Verse', null),
('Sarah Kemble Knight', 'A Master’s Degree', '253'),
('Sarah Wentworth Apthorp Morton', 'A Millionaire of Rough-and-Ready', '351'),
('Judith Sargent Stevens Murray', 'A Moosehead Journal', null),
('Thomas Paine', 'A Mountain Woman', null),
('Lucy Terry', 'An Alien Light', null),
('John Trumbull', 'An Ancient Spell', null),
('Royall Tyler', 'An Elephant’s Track, and Other Stories', null),
('Mercy Otis Warren', 'A New England Girlhood, Outlined From Memory', null),
('Phillis Wheatley', 'An Idyl of the South', '381'),
('John Woolman', 'A Night in Acadie', '281'),
('Jacob Abbott', 'An Imperative Duty', '388'),
('Bronson Alcott', 'An International Episode', '474'),
('Delia Salter Bacon', 'Anne Boleyn: A Tragedy', null),
('Robert Montgomery Bird', 'An Old-Fashioned Girl', null),
('Black Hawk', 'An Old-Fashioned Thanksgiving', null),
('Maria Gowen Brooks', 'Anthem', null),
('John Brougham', 'Anthology of Magazine Verse for 1913', null),
('William Wells Brown', 'Anthology of Magazine Verse for 1920, and Year Book of American Poetry', null),
('William Cullen Bryant', 'Anthology of Massachusetts Poets', null),
('Anna Ella Carroll', 'Anti-Slavery Poems of John Pierpont', null),
('Alice Cary', 'A Plea for Old Cap Collier', '396'),
('Phoebe Cary', 'A Poem on the Meditation of Nature', '350'),
('William Ellery Channing', 'A Poor Wise Man', '47'),
('Mary Boykin Miller Chesnut', 'A Princess of Mars', null),
('Lydia Maria Child', 'A Psalm of Deaths and Other Poems', null),
('Ada Clare', 'Aquidneck: A Poem', '67'),
('James Fenimore Cooper', 'A Reader’s Guide to William Gaddis’s The Recognitions', '403'),
('Maria Susanna Cummins', 'Arizona Nights', null),
('George William Curtis', 'Armazindy', null),
('Richard Henry Dana', 'A Roadside Harp: A Book of Verses', null),
('Rebecca Blaine Harding Davis', 'A Roman Lawyer in Jerusalem, First Century', null),
('Martin R. Delany', 'Artemis to Actaeon and Other Verse', null),
('David Dickson', 'A Sausage from Bologna: A Comedy in Four Acts', null),
('Frederick Douglass', 'A Son of the Sun', '82'),
('Mary Henderson Eastman', 'A Southern Flight', '450'),
('Elizabeth Fries Lummis Ellet', 'Assault on the Gods', null),
('Ralph Waldo Emerson', 'A Strange Manuscript Found in a Copper Cylinder', '258'),
('Margaret Fuller', 'A Strange Manuscript Found in a Copper Cylinder', '58'),
('William Lloyd Garrison', 'A Student’s History of American Literature', null),
('Caroline Howard Gilman', 'A Sweet Girl Graduate', null),
('Angelina Emily Grimké', 'Atlanta Offering: Poems', '159'),
('James Hall', 'At Sundown', null),
('Fitz-Greene Halleck', 'A Traveller from Altruria (original magazine edition)', null),
('Frances E.W. Harper', 'At the Beautiful Gate, and Other Songs of Faith', null),
('George Washington Harris', 'At the Earth’s Core', null),
('Nathaniel Hawthorne', 'Aunt Dice: The Story of a Faithful Slave', null),
('George Moses Horton', 'Avenging the Maine, A Drunken A. B., and Other Poems', '3'),
('Washington Irving', 'A Voice on the Wind, and Other Poems', '465'),
('Harriet A. Jacobs', 'A Voyage to the Fortunate Isles, Etc.', null),
('John P. Kennedy', 'A Waif of the Plains', null),
('Juliette Augusta Magill Kinzie', 'A Ward of the Golden Gate', null),
('Abraham Lincoln', 'A Wayside Lute', null),
('Henry Wadsworth Longfellow', 'A White Heron', null),
('Herman Melville', 'A Wonder-Book for Girls and Boys', null),
('Adah Isaacs Menken', 'Balcony Stories', '492'),
('Harriet Mann Miller', 'Ballads and Other Verses', null),
('Donald Grant Mitchell', 'Ballads of New England', null),
('Clement Clarke Moore', 'Ballads of Valor and Victory, Being Stories in Song from the Annals of America', '207'),
('Anna Cora Mowatt', 'Ballads, Lyrics, and Hymns', '294'),
('Mary Gove Nichols', 'Ballads, Patriotic and Romantic', null),
('Solomon Northup', 'Bark: A Polemic', null),
('Fitz-James O’Brien', 'Barna', null),
('Francis Parkman', 'Baxter’s Procrustes', null),
('Sara Payson Willis Parton', 'Bayou Folk', null),
('James Kirke Paulding', 'Beauty and the Beast', '203'),
('John Howard Payne', 'Beauty and the Beast, and Tales of Home', '340'),
('Mary Hayden Green Pike', 'Before Adam', '261'),
('Edgar Allan Poe', 'Behind a Mask: or, A Woman’s Power', null),
('Catharine Maria Sedgwick', 'Ben-Hur: A Tale of the Christ', null),
('L.H. Sigourney', 'Benito Cereno', null),
('William Gilmore Simms', 'Betty Zane', '233'),
('Seba Smith', 'Between Whiles', '153'),
('Ann Sophia Stephens', 'Beyond the Horizon', '38'),
('Harriet Beecher Stowe', 'Billy Budd', '306'),
('Henry David Thoreau', 'Biography and Poetical Remains of the Late Margaret Miller Davidson', null),
('Henry Timrod', 'Bits of Gossip', null),
('Sojourner Truth', 'Bitter-Sweet: A Poem', null),
('Jones Very', 'Blix', '304'),
('David Walker', 'Bloom / Blood: A Commemorative Poem in Three Parts', '216'),
('Mason Locke Weems', 'Blue Fairy Book', null),
('Frances Miriam Berry Whitcher', 'Born Again', '36'),
('Sarah Helen Power Whitman', 'Bound to Rise', '489'),
('Walt Whitman', 'Breakers and Granite', null),
('John Greenleaf Whittier', 'Brewster’s Millions', null),
('David Wilson', 'Bronchial Tangle, Heart System', null),
('Harriet E. Wilson', 'Burning Daylight', null),
('Charles Follen Adams', 'Burrowing In, Digging Out', null),
('Henry Adams', 'Buttered Side Down', null),
('William Taylor Adams', 'By Shore and Sedge', '7'),
('Louisa May Alcott', 'Can Such Things Be?', '181'),
('Isabella Macdonald Alden', 'Captain Salt in Oz', '486'),
('Thomas Bailey Aldrich', 'Caravan', null),
('Francesca Alexander', 'Cast Upon the Breakers', null),
('Horatio Alger', 'Cataloging Internet Resources: A Manual and Practical Guide', null),
('Elizabeth Anne Chase Akers Allen', 'Chameleon’s Cadmium', null),
('Mary Austin', 'Charlotte Temple', null),
('Joel Barlow', 'Chicago Poems', null),
('Katharine Lee Bates', 'Children of the Frost', '314'),
('L. Frank Baum', 'Chita: A Memory of Last Island', '180'),
('Clifford Whittingham Beers', 'Christmas Tales and Christmas Verse', '59'),
('Ethel Lynn Beers', 'City Ballads', '280'),
('David Belasco', 'City Festivals', null),
('Edward Bellamy', 'City Legends', null),
('Ambrose Bierce', 'Clotel, or The President’s Daughter (1835 edition)', null),
('Lillie Devereux Blake', 'Clotelle, or The Colored Heroine', null),
('Dion Boucicault', 'Cloth of Gold and Other Poems', null),
('Randolph Silliman Bourne', 'Colonel Carter of Cartersville', null),
('Hugh Henry Brackenridge', 'Come Live My Life', '293'),
('Gamaliel Bradford', 'Complete on-line works.', null),
('Alice Brown', 'Complete On-Line Works.', '116'),
('Orestes Augustus Brownson', 'Condensed Novels', '296'),
('Henry Cuyler Bunner', 'Condensed Novels Second Series: New Burlesques', null),
('Frances Hodgson Burnett', 'Confidence', null),
('John Burroughs', 'A Romance Illustrative of Negro Life North and South', '190'),
('George W. Cable', 'Cord and Creese', null),
('Abraham Cahan', 'Cornhuskers', null),
('Charles W. Chesnutt', 'Cow-Country', '85'),
('Kate Chopin', 'Custer, and Other Poems', null),
('Winston Churchill', 'Daddy-Long-Legs', '92'),
('James Freeman Clarke', 'Daisy Miller', '333'),
('Rebecca Sophia Clarke', 'Damaged Goods', null),
('Florence Van Leer Earle Nicholson Coates', 'Dangerous Days', '492'),
('Frank Moore Colby', 'Darkness and Dawn, ed.', null),
('Moncure Daniel Conway', 'Dartmouth Lyrics', '87'),
('Rose Terry Cooke', 'Dawn O’Hara, the Girl who Laughed', '262'),
('Ina Donna Coolbrith', 'Dear Enemy', null),
('Anna Julia Cooper', 'Deck', null),
('Stephen Crane', 'Democracy: An American Novel', null),
('Adelaide Crapsey', 'De Profundis', null),
('F. Marion Crawford', 'Dermot MacMorrogh, or, The Conquest of Ireland', null),
('Fanny Crosby', 'Descriptive Sketches of Nova Scotia, in Prose and Verse', null),
('Augustin Daly', 'Desert Gold: A Romance of the Border', null),
('Flora Adams Darling', 'Dialect Tales', null),
('Richard Harding Davis', 'Dis, Dat an’ Tutter: Poems', null),
('John William DeForest', 'Dorothy and the Wizard in Oz', null),
('Emily Dickinson', 'Dozens: A Poem', null),
('Mary Abigail Dodge', 'Dream Protocols', null),
('Mary Mapes Dodge', 'Dreams & Dust', null),
('Ignatius Donnelly', 'Dreams of Life: Miscellaneous Poems', '258'),
('Julia Caroline Ripley Dorr', 'Drift From Two Shores', '338'),
('Theodore Dreiser', 'Driftwood', '282'),
('W.E.B. Du Bois', 'Dust, and Short Works', null),
('Paul Laurence Dunbar', 'Dutch Courage and Other Stories', null),
('Edward Eggleston', 'East and West: Poems', null),
('Ernest F. Fenollosa', 'Eclipse', null),
('Eugene Field', 'Editorials from the Hearst Newspapers', null),
('James T. Fields', 'Eggs in the Lake', null),
('Martha Finley', 'Eliot: A Poem', null),
('Harrison Grey Fiske', 'Emma McChesney & Co.', null),
('Clyde Fitch', 'English Traits', null),
('Mary Anna Hallock Foote', 'Equinox and Other Poems', null),
('Harold Frederic', 'Erewhon Revisited', null),
('Mary E. Wilkins Freeman', 'Essays', null),
('Jessie Ann Benton Frémont', 'Including Biographies and Miscellaneous Pieces, in Prose and Poetry', null),
('Helen Hamilton Gardener', 'Essays: Second Series', null),
('Hamlin Garland', 'Essays and Poems', '133'),
('Jeannette Leonard Gilder', 'Esther, a Sacred Drama; With Judith, a Poem', '412'),
('William Hooker Gillette', 'Ethan Frome', '127'),
('Charlotte Perkins Gilman', 'Ethiope Lays', null),
('Avrom Goldfaden', 'Evangeline', '467'),
('Anna Katharine Green', 'Eve’s Diary', '33'),
('Charlotte Forten Grimké', 'Extracts From Adam’s Diary', '98'),
('Louise Imogen Guiney', 'Extract From Captain Stormfield’s Visit to Heaven', null),
('Edward Everett Hale', 'Fanny Herself', '487'),
('Lucretia Peabody Hale', 'Farm Ballads', null),
('Sarah Josepha Hale', 'Farm Festivals', '276'),
('Ida A. Husted Harper', 'Fern Leaves from Fanny’s Portfolio', '398'),
('Edward Harrigan', 'Field Stones', '309'),
('Joel Chandler Harris', 'Fifty Years & Other Poems', '53'),
('Bret Harte', 'Fisherman’s Luck and Some Other Uncertain Things', null),
('John Hay', 'Five Thousand Miles Underground, or, The Mystery of the Centre of the Earth', '200'),
('Paul Hamilton Hayne', 'Flame and Shadow', '134'),
('Lafcadio Hearn', 'Flying U Ranch', null),
('O. Henry', 'Forest Buds, From the Woods of Maine', '466'),
('James A. Herne', 'For Your Sweet Sake: Poems', '177'),
('Marietta Holley', 'Four Incarnations: New and Selected Poems, 1957-1991', '89'),
('Oliver Wendell Holmes', 'Four Springs', null),
('Pauline Hopkins', 'Frances Waldeaux', null),
('Richard Hovey', 'Frank’s Campaign: or, The Farm and the Camp', null),
('Bronson Howard', 'Freckles', null),
('Julia Ward Howe', 'Free Joe, and Other Georgian Sketches', null),
('William Dean llowells', 'Gadget Man', null),
('Elbert Hubbard', 'Garnered Sheaves', null),
('Helen Hunt Jackson', 'Gawayne and the Green Knight: A Fairy Tale', '390'),
('Henry James', 'General William Booth Enters Into Heaven and Other Poems', '293'),
('Sarah Orne Jewett', 'Gleanings', '142'),
('James Weldon Johnson', 'Gleanings of Quiet Hours', '178'),
('E.Z.C. Judson', 'Glinda of Oz', '2'),
('John La Farge', 'Good Wives (part 2 of Little Women)', '499'),
('Sidney Lanier', 'Graffiti d’Italia', null),
('Emma Lazarus', 'Grandmother’s Story, and Other Poems', null),
('Homer Lea', 'Grand’ther Baldwin’s Thanksgiving, With Other Ballads and Poems', null),
('Charles Godfrey Leland', 'Halo', null),
('Jack London', 'Handy Mandy in Oz', null),
('James Russell Lowell', 'Hans Breitmann’s Party, With Other Ballads', null),
('Steele MacKaye', 'Harlem Shadows: The Poems of Claude McKay', null),
('Helen Marot', 'Hawthorne', '321'),
('Brander Matthews', 'Haydon: An Artist’s Life', '272'),
('George Barr McCutcheon', 'He and She: or, A Poet’s Portfolio', '106'),
('Joaquin Miller', 'He Fell in Love With His Wife', '438'),
('S. Weir Mitchell', 'Helen of Troy, and Other Poems', '168'),
('William Vaughn Moody', 'Hell fer Sartain and Other Stories', null),
('Julia A. Moore', 'Herakles', null),
('Margaret Warner Morley', 'Herds', null),
('Ellen Louise Chandler Moulton', 'Her Father’s Daughter', null),
('Mary Noailles Murfree', 'Her First Appearance', null),
('Eliza Jane Poitevent Holbrook Nicholson', 'Herland', '93'),
('Frank Norris', 'Hermione and Her Little Group of Serious Thinkers', '133'),
('Thomas Nelson Page', 'Hermione, and Other Poems', '231'),
('Joseph Pennell', 'Her Prairie Knight, and Rowdy of the “Cross L”', '1'),
('Nora Perry', 'Hide and Seek', '267'),
('Sarah Morgan Bryan Piatt', 'Hills of Song', '463'),
('Maria Louise Pool', 'His Own People', '332'),
('Elizabeth Payson Prentiss', 'His Pa’s Romance', null),
('Howard Pyle', 'History as Literature, and Other Essays', null),
('Opie Read', 'Home Ballads and Poems', '294'),
('James Whitcomb Riley', 'House of Kidz', '211'),
('Harriet Jane Hanson Robinson', 'Howard Pyle’s Book of Pirates', '172'),
('O.E. Rölvaag', 'Howdy, Honey, Howdy', '246'),
('Susanna Rowson', 'How Salvator Won and Other Recitations', '178'),
('Edgar Evertson Saltus', 'Hymen', null),
('Benjamin Sanborn', 'Hymns of the Marshes', null),
('Margaret Elizabeth Munson Sangster', 'Hyperion: A Romance', null),
('Hannah Whitall Smith', 'Idyl of Work', '255'),
('Emma Southworth', 'Idyls and Lyrics of the Ohio Valley', '451'),
('Harriet Elizabeth Prescott Spofford', 'Idyls and Pastorals', null),
('Edmund Clarence Stedman', 'Illustrated Poems', null),
('Frank Richard Stockton', 'Illustrated Poems of Oliver Wendell Holmes', null),
('Richard Henry Stoddard', 'Imperium in Imperio', '117'),
('Ida M. Tarbell', 'In a Hollow of the Hills', '338'),
('Mary Virginia Hawes Terhune', 'Infatuation', '328'),
('Celia Laighton Thaxter', 'Infelicia', '233'),
('Augustus Thomas', 'In His Steps', null),
('Rose Alnora Hartwick Thorpe', 'Initials Only', null),
('Thomas B. Thorpe', 'In Memory of the Future', '76'),
('Mabel Loomis Todd', 'In Ole Virginia, or, Marse Chan and Other Stories', '472'),
('Kate Nichols Trask', 'In Simpkinsville: Character Tales', null),
('Frederick Jackson Turner', 'In the Bishop’s Carriage', null),
('Mark Twain', 'In the Cage', null),
('Mariana Alley Griswold Van Rensselaer', 'In the Carquinez Woods', '217'),
('Frances Auretta Fuller Victor', 'In the Land of the Living Dead: An Occult Story', '151'),
('Metta Victoria Fuller Victor', 'In the Solar Wind', '422'),
('Lewis Wallace', 'In the Tennessee Mountains', '388'),
('Elizabeth Stuart Phelps Ward', 'Iola Leroy: or, Shadows Uplifted', '429'),
('Susan Bogert Warner and Anna Bartlett Warner', 'Irradiations, Sand and Spray', null),
('Booker T. Washington', 'Island Tales', null),
('Jean Webster', 'Jaguar', null),
('Ida B. Wells-Barnett', 'Japanese Prints', null),
('Edward Noyes Westcott', 'Jerry of the Islands', null),
('Edith Wharton', 'John Barleycorn', '286'),
('Adeline Dutton Train Whitney', 'John Dough and the Cheru', '276'),
('Ella Wheeler Wilcox', 'A Sketch of His Life, With Selected Poems', '174'),
('Augusta Jane Evans Wilson', 'John March, Southerner', '217'),
('Owen Wister', 'Judith and Holofernes', null),
('Sarah Chauncey Woolsey', 'Jungle Tales of Tarzan', null),
('Constance Fenimore Woolson', 'Jurgen: A Comedy of Justice', null),
('Zitkala-Sa', 'Just David', null),
('Louis Adamic', 'Just Folks', '241'),
('Franklin Pierce Adams', 'Kansas Women in Literature', '346'),
('Léonie Adams', 'Kathrina: Her Life and Mine, in a Poem', '464'),
('Samuel Hopkins Adams', 'Kentucky Poems', '222'),
('George Ade', 'Keramos, and Other Poems', '436'),
('Conrad Aiken', 'Keziah Coffin', null),
('Maxwell Anderson', 'Kissing the Dancer & Other Poems', null),
('Regina M. Anderson', 'Knight Life', null),
('Sherwood Anderson', 'Kwaidan: Stories and Studies of Strange Things', null),
('Katharine Anthony', 'Laddie: A True Blue Story', '41'),
('Gertrude Atherton', 'Lady Baltimore', '337'),
('Joseph Auslander', 'Lady Freedom Among Us', '444'),
('Irving Babbitt', 'Lahoma', null),
('Irving Bacheller', 'Landed Natures', '60'),
('Ray Stannard Baker', 'Landmarks: The Lost Farm and Other Poems', '355'),
('Faith Baldwin', 'Landscape of Demons, and The Book of Sara', '265'),
('Djuna Barnes', 'Lars: A Pastoral of Norway', '230'),
('Philip Barry', 'Last Poems of James Russell Lowell', '395'),
('Vicki Baum', 'The Sisters’ tragedy, Wyndham Towers and Unguarded Gates', '262'),
('Sylvia Beach', 'Lavender and Old Lace', null),
('S.N. Behrman', 'Leaves of Grass (1855 edition, with commentary)', '483'),
('Robert Benchley', 'Leaves of Grass (1881-82 edition)', '209'),
('Stephen Vincent Benét', 'Leaves of Grass', '29'),
('Gwendolyn Bennett', 'Legends of New-England', null),
('Aline Frankau Bernstein', 'Legends of the Province House', '90'),
('Albert J. Beveridge', 'Life at Laurel Town in Anglo-Saxon Kansas', '481'),
('Earl Derr Biggers', 'Life in the Iron-Mills', '151'),
('John Peale Bishop', 'Life on the Mississippi', null),
('Marc Blitzstein', 'Life on the Mississippi', '158'),
('Maxwell Bodenheim', 'Life Without Principle', '470'),
('Arna Bontemps', 'Light: A Narrative Poem', null),
('Louis Bromfield', 'Li’l’ Gal', '453'),
('Cleanth Brooks', 'Lincoln and Other Poems', '481'),
('Van Wyck Brooks', 'Linda Condon', null),
('Margaret Wise Brown', 'Linden Rhymes (Halifax: E.G. Fuller, 1854)', null),
('Gelett Burgess', 'Lin McLean', null),
('Thornton W. Burgess', 'An Oration Delivered Before the Literary Societies of Dartmouth College', null),
('Kenneth Burke', 'Little Lord Fauntleroy', '413'),
('Edgar Rice Burroughs', 'Little Men', '348'),
('Virginia Lee Burton', 'Little Susy’s Six Birthdays', null),
('James Branch Cabell', 'Little Women (UK version: Part 1 of US version)', null),
('W.J. Cash', 'Little Women (US version: includes ‘Good Wives’)', null),
('Willa Cather', 'Loew’s Bridge: A Broadway Idyl', '218'),
('Raymond Chandler', 'Lost Face', '310'),
('John Jay Chapman', 'Love Ain’t Nothing But Sex Misspelled (1983 edition)', null),
('Leslie Charteris', 'Love Me Tomorrow', null),
('Mary Ellen Chase', 'Love of Life, and Other Stories', null),
('Irvin S. Cobb', 'Love Songs', null),
('Robert P. Tristram Coffin', 'Love-Songs of Childhood', null),
('George M. Cohan', 'Lulla', null),
('Marc Connelly', 'Lyrics (7th edition, 1909)', null),
('Jack Conroy', 'Lyrics and other poems', null),
('Jane Cowl', 'Lyrics for a Lute', null),
('Malcolm Cowley', 'Lyrics of Joy', null),
('George Cram', 'Lyrics of Life and Love', null),
('Hart Crane', 'Lyrics of Lowly Life', null),
('Frank Craven', 'Lyrics of Sunshine and Shadow', null),
('Harry Crosby', 'Mackinac and Lake Stories', null),
('Rachel Crothers', 'Madame de Treymes', null),
('Countee Cullen', 'Mae Madden', null),
('E.E. Cummings', 'Maggie, a Girl of the Streets', null),
('Ève Curie', 'Magnolia Leaves', null),
('Donald Davidson', 'Making Space For Our Living', null),
('H.L. Davis', 'Main Street', null),
('Margaret Deland', 'Main Street, and Other Poems (Doran, 1917)', null),
('Floyd Dell', 'Man the Reformer', '403'),
('Hilda Doolittle (H.D.)', 'Margret Howth: A Story of To-day (second edition)', '384'),
('John Dos Passos', 'Mark Twain’s Speeches', '295'),
('Ruth Draper', 'Martin Eden', '237'),
('Alice Dunbar Nelson', 'Maruja', '431'),
('Fannie Pearson Hardy Eckstorm', 'Maryland, My Maryland, and Other Poems', '221'),
('T.S. Eliot', 'Mary Marie', '379'),
('John Erskine', 'McTeague, A Story of San Francisco', '430'),
('James T. Farrell', 'Mechitza', null),
('William Faulkner', 'Megda', null),
('Jessie Redmon Fauset', 'Melanie and Other Poems', null),
('Kenneth Fearing', 'Melodies, Duets, Trios, Songs, and Ballads', '293'),
('Edna Ferber', 'Memoirs of Anne C. L. Botta', '3'),
('Dorothy Canfield Fisher', 'Memories of Jane Cunningham Croly', '284'),
('Rudolph Fisher', 'Men of Iron', null),
('Dudley Fitts', 'Men, Women and Ghosts', null),
('F. Scott Fitzgerald', 'Mercedes: A Drama in Two Acts', null),
('Douglas Southall Freeman', 'Merlin', '92'),
('Robert Frost', 'Merry Tales', '52'),
('Henry Blake Fuller', 'Michael, Brother of Jerry', null),
('Wanda Hazel Gág', 'Mindflight', null),
('Zona Gale', 'Minions of the Moon: A Little Book of Song and Story', null),
('Erle Stanley Gardner', 'Miriam: A Dramatic Poem', null),
('Howard R. Garis', 'Miss Civilization: A Comedy in One Act', null),
('Katharine Elizabeth Fullerton Gerould', 'Miss Lulu Bett (stage play)', '51'),
('Ira Gershwin', 'Modern American Poetry: An Introduction', '373'),
('Khalil Gibran', 'Monsieur Beaucaire', '462'),
('Ellen Glasgow', 'Monsieur Motte', null),
('Susan Glaspell', 'Moon-Face, and Other Stories', null),
('Zane Grey', 'Was Neil Armstrong Really the First Man on the Moon?', null),
('Angelina Weld Grimké', 'Moran of the Lady Letty', '424'),
('Edgar A. Guest', 'Mosses from an Old Manse', '483'),
('Louise Closser Hale', 'Mother', null),
('Moyshe Leyb Halpern', 'Mother: A Story', null),
('Moss Hart', 'Mountain Interval', null),
('Lillian Hellman', 'Mudfog and Other Sketches', null),
('Ernest Hemingway', 'Mug', null),
('Joseph Hergesheimer', 'My Antonia', '399'),
('DuBose Heyward', 'My Favorite Murder', '89'),
('Granville Hicks', 'My Mark Twain', '38'),
('Ralph Hodgson', 'My Garden Acquaintance', '141'),
('Sidney Howard', 'My Little Sister', '92'),
('E.W. Howe', 'Myth and Romance', null),
('Langston Hughes', 'Nathaniel Hawthorne and His Wife: A Biography', null),
('Zora Neale Hurston', 'Nature and Art: A Poem', null),
('Robinson Jeffers', 'Nature, Addresses, and Lectures', null),
('Osa Johnson', 'Nature-Notes and Impressions, in Prose and Verse', null),
('George S. Kaufman', 'New Poems', null),
('George Kelly', 'Night of Power (1994 edition)', null),
('Joyce Kilmer', 'Night of the Dragon’s Blood (electronic edition)', null),
('George Lyman Kittredge', 'Nineveh, and Other Poems', null),
('Oliver La Farge', 'Northern Georgia Sketches', null),
('Ring Lardner', 'North of Boston', null),
('Nella Larsen', 'Not a Man, and Yet a Man', '178'),
('Meridel Le Sueur', 'Not Be Essence That Cannot Be (with additional poems)', null),
('Sinclair Lewis', 'Nothing to Do: A Tilt at Our Best Society', null),
('Vachel Lindsay', 'Old and New World Lyrics', null),
('Hugh Lofting', 'Old Caravan Days (Boston: D. Lothrop, c1884)', '465'),
('H.P. Lovecraft', 'Old Creole Days', '30'),
('Amy Lowell', 'Old-Fashioned Roses', '167'),
('John Livingston Lowes', 'Old Kaskaskia (Boston: Houghton, Mifflin, 1893)', '163'),
('Mina Loy', 'On Basilisk Station', '315'),
('Clare Boothe Luce', 'One Basket: Thirty-One Short Stories', '459'),
('Charles MacArthur', 'One Man’s Initiation: 1917 (1920 edition)', null),
('Percy MacKaye', 'One of Ours', null),
('Archibald MacLeish', 'On the Makaloa Mat', null),
('Frances Marion', 'O Pioneers!', '250'),
('Edwin Markham', 'Options', '343'),
('Edgar Lee Masters', 'Original Poems', '169'),
('F.O. Matthiessen', 'Other Things Being Equal', '452'),
('Robert McAlmon', 'Our Little Harry, and Other Poems and Stories', '489'),
('Claude McKay', 'Our Mr. Wrenn', '241'),
('H.L. Mencken', 'Our Nig: or, Sketches from the Life of a Free Black', null),
('Edna St. Vincent Millay', 'Our Old Home: A Series of English Sketches', null),
('Alice Duer Miller', 'Ovid’s Elegies', null),
('Margaret Mitchell', 'Ozma of Oz', null),
('Harriet Monroe', 'Ozoplaning with the Wizard of Oz', '271'),
('Marianne Moore', 'Padre Ignacio', '354'),
('Paul Elmer More', 'Painted Windows', '205'),
('John Gneisenau Neihardt', 'Perspectives in American Literature', '451'),
('Richard Nugent', 'Parnassus on Wheels', '361'),
('Rose Cecil O’Neill', 'Passages from the American Note-Books of Nathaniel Hawthorne', '6'),
('Clifford Odets', 'Paul Prescott’s Charge', '65'),
('Tillie Olsen', 'Penelope’s Experiences in Scotland', null),
('Dorothy Parker', 'Penelope’s Irish Experiences', null),
('Vernon L. Parrington', 'Penelope’s Postscripts', null),
('Josephine Preston Peabody', 'Penrod', '27'),
('Lucy Fitch Perkins', 'Penrod and Sam', '186'),
('Maxwell Perkins', 'Personal Recollections of Joan of Arc', '416'),
('Ralph Barton Perry', 'Personal Recollections of Nathaniel Hawthorne', '366'),
('David Pinski', 'Peter Parley’s Juvenile Tales (1855)', null),
('Eleanor Hodgman Porter', 'Peter Parley’s Story of the Little Gardener', null),
('Gene Stratton Porter', 'Peter Parley’s Winter Evening Tales', null),
('Katherine Anne Porter', 'Phase Language', null),
('Ezra Pound', 'Philo: An Evangeliad', '371'),
('Ellery Queen', 'Philosophy 4', '292'),
('Philip Rahv', 'Phoenixiana: or, Sketches and Burlesques', '337'),
('John Crowe Ransom', 'Pigs Is Pigs', '338'),
('Marjorie Kinnan Rawlings', 'Pike County Ballads and Other Pieces', null),
('Lizette Woodworth Reese', 'Pirate’s Song', null),
('Alice Caldwell Hegan Rice', 'Plea of the Negro Soldier, and a Hundred Other Poems', null),
('Elmer Rice', 'Pocahontas, and Other Poems', null),
('Laura Riding', 'Poem Outlines', null),
('Ameen Rihani', 'Poems for Children', null),
('Mary Roberts Rinehart', 'Poems Here at Home', null),
('Elizabeth Madox Roberts', 'Poems: Medley and Palestina', null),
('Kenneth Roberts', 'Poems Now First Collected', null),
('Edwin Arlington Robinson', 'Poems of House and Home', null),
('Henry Roth', 'Poems of James Russell Lowell', null),
('Damon Runyon', 'Poems of Paul Hamilton Hayne', null),
('Carl Sandburg', 'Poems of Pleasure', '137'),
('Anne Douglas Sedgwick', 'Poems of Power', '216'),
('Ernest Thompson Seton', 'Poems of Religion and Society', '188'),
('Charles Monroe Sheldon', 'Poems of the Orient', null),
('Robert E. Sherwood', 'Poems: Patriotic, Religious, Miscellaneous', null),
('Constance Lindsay Skinner', 'Poetical Remains of the Late Lucretia Maria Davidson', null),
('Gertrude Stein', 'Poetic Studies', '490'),
('Wallace Stevens', 'Poetry: A Satire', '215'),
('Michael Strange', 'Poganuc People: Their Loves and Lives', '474'),
('Edward Stratemeyer', 'Pollyanna', '61'),
('Genevieve Taggard', 'Pollyanna Grows Up', '413'),
('Booth Tarkington', 'Ponkapog Papers', '273'),
('Allen Tate', 'Poor Richard’s Almanack', null),
('Sara Teasdale', 'Prejudices: First Series', null),
('Albert Payson Terhune', 'Pro Patria: Verses Chiefly Patriotic', null),
('Dorothy Thompson', 'Proposition 31', null),
('Wallace Henry Thurman', 'Pure Daughter', null),
('Eunice Tietjens', 'Ragged Dick', null),
('Jean Toomer', 'An Estimate of his Character and Genius', '91'),
('Ridgely Torrence', 'Ramona', '238'),
('Lionel Trilling', 'Reality Inspector', '275'),
('S.S. Van Dine', 'Recollections of a Southern Matron', null),
('Carl Van Doren', 'Renascence and Other Poems', null),
('Mark Van Doren', 'Representative American Poetry', null),
('Henry Van Dyke', 'Representative Men', null),
('Carl Van Vechten', 'Retinue and Other Poems', null),
('Carolyn Wells', 'Revolution, and Other Essays', null),
('Nathanael West', 'Rezánov', '91'),
('Laura Ingalls Wilder', 'Rhymes of Childhood', '129'),
('Thornton Wilder', 'Rhymes of Our Planet', '269'),
('William Carlos Williams', 'Riders of the Purple Sage', '244');