INSERT INTO address (street)
VALUES
('Baker Road'),
('Baldwin Lane'),
('Balsam Road'),
('Bancroft Avenue'),
('Barbara Lane'),
('Barrows Road'),
('Bartlett Circle'),
('Batchelder Road'),
('Bay State Road'),
('Beacon Street'),
('Bear Hill Road'),
('Beaver Road'),
('Beech Street'),
('Belmont Street'),
('Benjamin Lane'),
('Benton Circle'),
('Berkeley Street'),
('Bethesda Lane'),
('Beverly Road'),
('Birch Meadow Drive'),
('Birch Road'),
('Blueberry Lane'),
('Bolton Street'),
('Bond Street'),
('Border Road'),
('Boswell Road'),
('Boyce Street'),
('Bradford Road'),
('Brande Court'),
('Brentwood Drive'),
('Breton Circle'),
('Brewer Lane'),
('Briarwood Avenue'),
('Brook Street'),
('Browning Terrace'),
('Buckingham Drive'),
('Buckskin Drive'),
('Bunker Avenue'),
('C Street'),
('California Road'),
('Canterbury Drive'),
('Cape Cod Avenue'),
('Carnation Circle'),
('Carriage Lane'),
('Catherine Avenue'),
('Causeway Road'),
('Cedar Street'),
('Center Avenue'),
('Chapel Hill Drive'),
('Chapin Avenue'),
('Charles Street'),
('Chequessett Road'),
('Cherry Lane Drive'),
('Chestnut Road'),
('Chute Street'),
('Clover Circle'),
('Colburn Avenue'),
('Colburn Road'),
('Cold Spring Road'),
('Collins Avenue'),
('Colonial Drive'),
('Condor Road'),
('Coolidge Road'),
('Copeland Avenue'),
('Cory Lane'),
('Cottage Park'),
('Countryside Lane'),
('County Road'),
('Courtyard Place'),
('Covey Hill Road'),
('Criterion Street'),
('Crocus Lane'),
('Crosby Road'),
('Cross Street'),
('Cumberland Road'),
('Curtis Street'),
('D Street'),
('Dana Road'),
('Davis Lane'),
('Dean Road'),
('Deborah Drive'),
('Deer Path Lane'),
('Deering Street'),
('Dividence Road'),
('Dorchester Street'),
('Dragon Court'),
('Duck Road'),
('Dudley Street'),
('Dunbar Road'),
('Dustin Road'),
('E Street'),
('Eastway'),
('Eaton Street'),
('Echo Avenue'),
('Edgemont Avenue'),
('Edwin Street'),
('Elderberry Lane'),
('Elliott Street'),
('Ellis Avenue'),
('Elm Street'),
('Emerald Drive'),
('Emerson Street'),
('Enos Circle'),
('Essex Street'),
('Estate Lane'),
('Evergreen Road'),
('F Street'),
('Fairchild Drive'),
('Fairmount Road'),
('Fairview Avenue'),
('Family Circle'),
('Federal Street'),
('Field Pond Drive'),
('Fielding Road'),
('Forest Glen Road'),
('Forest Street'),
('Foster Circle'),
('Fox Run Lane'),
('Francis Drive'),
('Frank Tanner Drive'),
('Franklin Street'),
('Franklin Terrace'),
('Fremont Street'),
('Fulton Street'),
('Gardner Road'),
('Garrett Road'),
('Gateway Circle'),
('Gavin Circle'),
('Gazebo Circle'),
('General Way'),
('George Street'),
('Gilmore Avenue'),
('Gleason Road'),
('Glen Road'),
('Glenmere Circle'),
('Glidden Way'),
('Gould Street'),
('Governors Drive'),
('Grand Street'),
('Grandview Road'),
('Granger Avenue'),
('Grant Street'),
('Green Street'),
('Greenwood Road'),
('Gregory Lane'),
('Grey Coach Lane'),
('Grey Coach Road'),
('Greystone Way'),
('Grove Street'),
('H Street'),
('Hampshire Road'),
('Hancock Street'),
('Hanscom Avenue'),
('Harnden Street'),
('Harold Avenue'),
('Harriman Avenue'),
('Harrison Street'),
('Hartshorn Street'),
('Harvard Street'),
('Harvest Road'),
('Haven Street'),
('Haverhill Street'),
('Haystack Road'),
('Heather Drive'),
('Hemlock Road'),
('Henzie Street'),
('Heritage Drive'),
('High Street'),
('Highland Road'),
('Highland Street'),
('Hillcrest Road'),
('Hillside Road'),
('Hodson Lane'),
('Holly Road'),
('Hopkins Street'),
('Howard Street'),
('Hunt Street'),
('Hurlburt Road'),
('Ide Street'),
('Indian Tree Lane'),
('Indiana Avenue'),
('Intervale Terrace'),
('Irving Street'),
('Ivy Lane'),
('Jacob Way'),
('Jadem Terrace'),
('James Road'),
('Jefferson Circle'),
('Jere Road'),
('Jessica Circle'),
('Johanna Drive'),
('John Carver Road'),
('John Street'),
('John Street Court'),
('Johnston Circle'),
('Joseph Way'),
('Juniper Circle'),
('Keith Road'),
('Kelch Road'),
('Kenneth Road'),
('Kensington Avenue'),
('Kieran Road'),
('King Street'),
('Kingston Street'),
('Knollwood Road'),
('Kurchian Lane'),
('Kylie Drive'),
('Lafayette Road'),
('Lakeview Avenue'),
('Landers Road'),
('Laneton Way'),
('Larch Lane'),
('Latham Lane'),
('Laurel Lane'),
('Lawrence Road'),
('Leaning Elm Drive'),
('Lee Street'),
('Lewis Street'),
('Libby Avenue'),
('Lilah Lane'),
('Lincoln Street'),
('Linden Street'),
('Lindsay Lane'),
('Line Road'),
('Linnea Lane'),
('Lisa Lane'),
('Locust Street'),
('Longfellow Road'),
('Longview Road'),
('Longwood Road'),
('Lothrop Road'),
('Louanis Drive'),
('Lowell Street'),
('Lucy Drive'),
('Lynn Village Way'),
('Macintosh Road'),
('Macmillan Way'),
('Main Street'),
('Manning Street'),
('Maple Ridge Road'),
('Maple Street'),
('Margaret Road'),
('Mark Avenue'),
('Marla Lane'),
('Martin Road'),
('Meadow Brook Lane'),
('Melbourne Avenue'),
('Melendy Drive'),
('Michelini Lane'),
('Middle Street'),
('Middlesex Avenue'),
('Milepost Road'),
('Mill Street'),
('Milton Road'),
('Mineral Street'),
('Minot Street'),
('Morgan Park'),
('Mount Vernon Street'),
('Munroe Avenue'),
('Nelson Avenue'),
('Newcrossing Road'),
('Nichols Road'),
('Norman Road'),
('North Street'),
('Nugent Lane'),
('Oak Ridge Road'),
('Oak Street'),
('Oakland Road'),
('Old Farm Road'),
('Old Mill Lane'),
('Orange Street'),
('Orchard Park Drive'),
('Ordway Terrace'),
('Osborne Avenue'),
('Overlook Road'),
('Palmer Hill Avenue'),
('Park Avenue'),
('Parker Street'),
('Parkman Road'),
('Parkview Road'),
('Parsons Lane'),
('Partridge Road'),
('Pasture Road'),
('Pearl Street'),
('Pennsylvania Avenue'),
('Percy Avenue'),
('Perkins Avenue'),
('Pierce Street'),
('Pilgrim Road'),
('Pine Avenue'),
('Pine Ridge Circle'),
('Pine Ridge Road'),
('Pinevale Avenue'),
('Pitman Drive'),
('Pleasant Street'),
('Plymouth Road'),
('Pondmeadow Drive'),
('Pondview Lane'),
('Pratt Street'),
('Prescott Street'),
('Priscilla Road'),
('Prospect Street'),
('Puritan Road'),
('Putnam Road'),
('Rachel Road'),
('Randall Road'),
('Reading Terrace'),
('Red Gate Lane'),
('Redfield Road'),
('Rice Road'),
('Richards Road'),
('Ridge Road'),
('Riverside Drive'),
('Robert Road'),
('Robin Road'),
('Rocky Road'),
('Roma Lane'),
('Rustic Lane'),
('Salem Street'),
('Sanborn Lane'),
('Sanborn Street'),
('Sandra Lane'),
('School Street'),
('Scotland Road'),
('Scout Hill Lane'),
('Selfridge Road'),
('Shackford Road'),
('Shady Hill Lane'),
('Shelby Road'),
('Sherwood Road'),
('Shore Road'),
('Short Street'),
('Small Lane'),
('Smith Avenue'),
('South Street'),
('Spring Street'),
('Springvale Road'),
('Spruce Road'),
('State Route'),
('State Route 28'),
('Stewart Road'),
('Stone Well Road'),
('Strawberry Hill Lane'),
('Sturges Road'),
('Summer Avenue'),
('Summit Drive'),
('Sumner Chaney Place'),
('Sumner Cheney Place'),
('Sunnyside Avenue'),
('Sunset Rock Lane'),
('Susan Drive'),
('Swan Road'),
('Sweetser Avenue'),
('Sylvan Road'),
('Symonds Way'),
('Tamarack Road'),
('Tanglewood Circle'),
('Tarpin Terrace'),
('Temple Street'),
('Tennyson Circle'),
('Tennyson Road'),
('Ter Park'),
('Thomas Drive'),
('Thorndike Street'),
('Timberneck Drive'),
('Timothys Place'),
('Torre Street'),
('Tower Road'),
('Track Road'),
('Twin Oaks Road'),
('Union Street'),
('Vale Road'),
('Van Norden Road'),
('Varney Circle'),
('Verde Circle'),
('Victoria Avenue'),
('Village Street'),
('Vine Street'),
('Virginia Circle'),
('Virginia Road'),
('Vista Avenue'),
('W Hill Circle'),
('Wakefield Street'),
('Walkers Brook Drive'),
('Walnut Street'),
('Warren Avenue'),
('Washington Street'),
('Waverly Road'),
('Wells Road'),
('Wenda Street'),
('Wentworth Road'),
('Wescroft Road'),
('West Street'),
('Weston Road'),
('White Oaks Lane'),
('Whitehall Lane'),
('Whittier Road'),
('Willard Road'),
('William Road'),
('Willow Street'),
('Wilson Street'),
('Winslow Road'),
('Winter Street'),
('Winthrop Avenue'),
('Woburn Street'),
('Wood End Lane'),
('Woodbine Street'),
('Woodland Street'),
('Woodward Avenue'),
('Zachary Lane'),
('Abbey Lane'),
('Abbey Street'),
('Alvord Place'),
('Alvord Street'),
('Amherst Road'),
('Amherst Street'),
('Ann Street'),
('Apple Road'),
('Applewood Lane'),
('Art Street'),
('Ashfield Lane'),
('Ashton Lane'),
('Atwood Road'),
('Bach Lane'),
('Baker Street'),
('Bara Lane'),
('Bardwell Street'),
('Bartlett Street'),
('Bayon Drive'),
('Belmont Avenue'),
('Benger Avenue'),
('Benoit Lane'),
('Berwyn Street'),
('Berwyn Street Exd'),
('Birch Hill Road'),
('Birchwood Place'),
('Blueberry Bnd'),
('Bombardier Street'),
('Boynton Avenue'),
('Brainerd Street'),
('Briar Spring Lane'),
('Bridge Street'),
('Bridgeman Lane'),
('Brigham Road'),
('Brittany Road'),
('Broad Street'),
('Brock Way'),
('Brockway Lane'),
('Bunker Hill'),
('Burnett Avenue'),
('Burns Way'),
('Buttonfield Lane'),
('Camden Street'),
('Camp Perkins Road'),
('Canal Street'),
('Carew Street'),
('Carlton Street'),
('Carol Ann Drive'),
('Cedar Ridge'),
('Center Street'),
('Central Avenue'),
('Charon Terrace'),
('Chateau Drive'),
('Chestnut Hill Road'),
('Chileab Road'),
('Church Street'),
('College Street'),
('College View Hts'),
('Columbia Street'),
('Commercial Drive'),
('Conti Drive'),
('Cordes Court'),
('Cornell Street'),
('Cote Boulevard'),
('Cottage Avenue'),
('Country Lane'),
('Cove Island Road'),
('Crescent Lane'),
('Crystal Lane'),
('Cypress Drive'),
('Dale Street'),
('Dartmouth Street'),
('Davina Street'),
('Dayton Street'),
('Dickinson Farm Road'),
('Doane Terrace'),
('Douglas Avenue'),
('Dove Hill'),
('Dover Road'),
('Dunlap Place'),
('E Carew Street'),
('E Parkview Drive'),
('E School Street'),
('E Street Court'),
('East Street'),
('Easy Street'),
('Edgewater Lane'),
('Edison Drive'),
('Enterprise Street'),
('Faculty Lane');